### ISSUE TITLE
SSD detector doesn't work correctly

### ISSUE THREAD

**Issue by nvnnghia** [Smorodov/Multitarget-tracker#65]
Hi, Thanks very much for sharing the code, I run your project using SSD detector, the result I got is very bad, there are many wrong detection. Do you have any ideas? Thank you.

**Comment by Nuzhny007** [comment]
Hi!
It's the first implementation without testing and other. The SSD detector have some params: https://github.com/Smorodov/Multitarget-tracker/blob/master/Detector/DNNDetector.cpp#L46
I will make API for they but jast now you can set confidenceThreshold 0.3 or bigger.

**Comment by Nuzhny007** [comment]
Thank you!
It was my error. I fixed it: https://github.com/Smorodov/Multitarget-tracker/pull/66

**Comment by nvnnghia** [comment]
The problem is still there, the coordinates are changed in a different way. Please check again. Thank you.

**Comment by Nuzhny007** [comment]
Ok, I need additional info.
I'm starting tracker with params: ./MultitargetTracker ../data/atrium.avi --gpu=0 -e=5 -o=at_ssd.mp4
And result: https://www.dropbox.com/s/ht96sakpafbdeth/at_ssd.mp4?dl=0
I think than it is correct. And you? Can you show video with wrong coordinates?

**Comment by Nuzhny007** [comment]
And you can see new PR with another example: https://github.com/Smorodov/Multitarget-tracker/pull/67

**Comment by nvnnghia** [comment]
Thank you very much for your kindly support. SSD detector is awesome now.
